export const queryKeys = {
  authMe: ["auth", "me"] as const,
  meta: ["meta"] as const,
  appMeta: ["app-meta"] as const,
  health: ["health"] as const,
  managedProjects: ["managed-projects"] as const,
  appProjects: ["app-projects"] as const,
  appBillingSummary: ["app-billing-summary"] as const,
  appBillingRequests: (limit: number) => ["app-billing-requests", limit] as const,
  appNotifications: (limit: number) => ["app-notifications", limit] as const,
  appProjectAccess: (projectId: number) => ["app-project-access", projectId] as const,
  appProjectOverview: (projectId: number) => ["app-project-overview", projectId] as const,
  signalHub: (limit: number, withinHours: number) =>
    ["signalhub", "upcoming", limit, withinHours] as const,
  appSignalHub: (limit: number, withinHours: number) =>
    ["app-signalhub", "upcoming", limit, withinHours] as const,
  walletConfigs: ["wallet-configs"] as const,
  userWalletConfigs: ["user-wallet-configs"] as const,
  wallets: (project: string) => ["wallets", project] as const,
  userWallets: (project: string) => ["user-wallets", project] as const,
  minutes: (project: string, from: number, to: number) =>
    ["minutes", project, from, to] as const,
  leaderboard: (project: string, top: number) => ["leaderboard", project, top] as const,
  delays: (project: string, limit: number) => ["event-delays", project, limit] as const,
  tax: (project: string) => ["project-tax", project] as const,
  runtimePause: ["runtime-pause"] as const,
  dbBatch: ["runtime-db-batch"] as const,
  projectScheduler: ["project-scheduler-status"] as const,
  overviewActive: (project: string) => ["overview-active", project] as const,
  adminProjectOverview: (projectId: number) => ["admin-project-overview", projectId] as const,
  appOverviewActive: (project: string) => ["app-overview-active", project] as const,
  scanJob: (jobId: string) => ["scan-job", jobId] as const,
  adminUsers: ["admin-users"] as const,
  adminUsersList: (q: string, status: string, role: string) =>
    ["admin-users", q, status, role] as const,
  adminUserDetail: (userId: number) => ["admin-user", userId] as const,
  adminUserWallets: (userId: number) => ["admin-user-wallets", userId] as const,
  adminUserCreditLedger: (userId: number) => ["admin-user-credit-ledger", userId] as const,
  adminUserProjectAccess: (userId: number) => ["admin-user-project-access", userId] as const,
  adminBillingRequests: (status: string, q: string, limit: number) =>
    ["admin-billing-requests", status, q, limit] as const,
  legacyApis: ["legacy-apis"] as const,
};
